// wc/src/components/z-box.tsx
import { c, css } from 'atomico'
import { boxProps, getBoxHostStyle } from '../shared/box-schema'
import { boxLayoutStyles } from '../shared/box-styles'

const baseStyles = css`
	:host {
		box-sizing: border-box;
	}
`

export const ZBox = c(
	(props) => (
		<host shadowDom style={getBoxHostStyle(props)}>
			<slot />
		</host>
	),
	{
		props: boxProps,
		styles: [baseStyles, boxLayoutStyles]
	}
)

customElements.define('z-box', ZBox)

// src/components/z-box.tsx
import { defineElement } from '../shared/define-element'
import { c, css } from 'atomico'
import { boxProps, getBoxHostStyle } from '../shared/box-schema'
import { boxLayoutStyles } from '../shared/box-styles'

const baseStyles = css`
	:host {
		box-sizing: border-box;
	}
`

export const ZBox = c(
	(props) => (
		<host shadowDom style={getBoxHostStyle(props)}>
			<slot />
		</host>
	),
	{
		props: boxProps,
		styles: [baseStyles, boxLayoutStyles]
	}
)

defineElement('z-box', ZBox)
